defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 7ef85da9-0723-4cc8-b6b8-9df83b858b76 # Contact
handle: contact
maxAuthors: 1
name: Contact
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  d9d1ae21-b5ed-442d-bc28-0e3aa8b8c39b: # Craft 5
    enabledByDefault: true
    hasUrls: true
    template: contact.twig
    uriFormat: contact
type: single
