defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 33bed828-65a4-4941-b936-034931852a48 # Locations
handle: locations
maxAuthors: 1
name: Locations
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  d9d1ae21-b5ed-442d-bc28-0e3aa8b8c39b: # Craft 5
    enabledByDefault: true
    hasUrls: true
    template: locations/_entry.twig
    uriFormat: 'locations/{slug}'
structure:
  maxLevels: 1
  uid: 717355ee-018c-4529-96ad-98696f9d5005
type: structure
